version: '3.8'
services:
    api:
        container_name: nestjsapi
        build: .
        volumes:
        - ./src:/server/src/
        - ./storage:/server/storage
        - ./.env:/server/.env
        restart: always
        ports:
        - 3000:3000
        networks:
        - nestjsnetwork

networks:
  nestjsnetwork:
    external: true
    driver: overlay